[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.3"
env_logger = "0.8"
diesel = { version = "2.0.0", features = ["postgres", "r2d2"] }
dotenvy = "0.15"
rfd = "0.11.3"
image = "0.24.6"
db = { path = "../db" }
